# Generated by Django 4.2.2 on 2023-07-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy_app', '0004_remove_meetup_end_time_meetup_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
