# Generated by Django 4.2.2 on 2023-07-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy_app', '0005_meetup_year_in_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='suit',
            field=models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], default=3),
        ),
    ]
